version: '3' 
services:
  docker-nebteans:
    image: openkbs/netbeans
    build:
      context: ./Dockerfile
    container_name: docker-netbeans
    environment:
      - USER_ID=${USER_ID:-1100}
      - GROUP_ID=${GROUP_ID:-1100}
    env_file:
      - ./docker.env
    volumes:
      - ./.netbeans:/home/developer/.netbeans
      - ./workspace:/home/developer/workspace

